# generated by stubbs:add-option
# Tue Sep  4 14:57:33 PDT 2012

# print USAGE and exit
rerun_option_error() {
    [ -z "$USAGE"  ] && echo "$USAGE" >&2
    [ -z "$SYNTAX" ] && echo "$SYNTAX $*" >&2
    return 2
}

# check option has its argument
rerun_option_check() {
    [ "$1" -lt 2 ] && rerun_option_error
}

# options: [failure_regex file maxtries poll_interval progress success_regex]
while [ "$#" -gt 0 ]; do
    OPT="$1"
    case "$OPT" in
          -f|--failure_regex) rerun_option_check $# ; FAILURE_REGEX=$2 ; shift ;;
  -F|--file) rerun_option_check $# ; FILE=$2 ; shift ;;
  -m|--maxtries) rerun_option_check $# ; MAXTRIES=$2 ; shift ;;
  -i|--interval) rerun_option_check $# ; INTERVAL=$2 ; shift ;;
  -P|--progress) rerun_option_check $# ; PROGRESS=$2 ; shift ;;
  -s|--success_regex) rerun_option_check $# ; SUCCESS_REGEX=$2 ; shift ;;
        # unknown option
        -?)
            rerun_option_error
            ;;
        # end of options, just arguments left
        *)
          break
    esac
    shift
done

# If defaultable options variables are unset, set them to their DEFAULT
[ -z "$INTERVAL" ] && INTERVAL="30"

# Check required options are set
[ -z "$MAXTRIES" ] && { echo "missing required option: --maxtries" >&2 ; return 2 ; }

#
return 0
