#!/usr/bin/env bash

#/ command: waitfor:port-open: "check if a network port is open for connections"
#/ usage: rerun waitfor:port-open  --interval <30>  --host <"">  --port <> 
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: INTERVAL HOST PORT


. $RERUN_MODULE_DIR/lib/functions.sh port-open || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}


set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"


# Command implementation
# ----------------------

nc -w $INTERVAL -z $HOST $PORT || rerun_die 1 "Could not connect to $HOST:$PORT"

#
exit $?

