#!/usr/bin/env bash

#/ command: waitfor:seconds: "wait for specified seconds"
#/ usage: rerun waitfor:seconds [ --interval <30>] 
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: INTERVAL

. $RERUN_MODULE_DIR/lib/functions.sh seconds || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"


# Command implementation
# ----------------------

[[ "$INTERVAL" =~ [0-9]+ ]] || rerun_die 2 'interval must be an interger.'

sleep "$INTERVAL"


# Done. Exit with last command exit status.
exit $?

