#!/usr/bin/env bash

#/ command: waitfor:file-exists: "wait for the file to exist"
#/ usage: rerun waitfor:file-exists  --file <>  --interval <30>  --maxtry <10> 
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: FILE INTERVAL MAXTRY

. $RERUN_MODULE_DIR/lib/functions.sh file-exists || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}


set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"


# Command implementation
# ----------------------

declare -i count=0 max=$MAXTRY sleep=$INTERVAL
while (( count <= max ))
do
    if ! test -f "$FILE"
    then  progress_tic "."; # output a progress string.
    else  break; # found successful startup message.
    fi
    (( count += 1 ))  ; # increment attempts counter.    
    (( count == max )) && {
        rerun_log warn "FAIL: Reached max try file exists: $FILE. Exiting."
        exit 1
    }
    sleep $sleep; # wait before trying again.
done

echo "OK: $(ls -l $FILE)"

# Done. Exit with last command exit status.
exit $?

