# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Fri May  4 20:15:57 CDT 2018
#
#/ usage: waitfor:ping  --host <"">  --interval <30> [ --maxtry <>] 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
#
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {
  
    unrecognized_args=()

    while (( "$#" > 0 ))
    do
        OPT="$1"
        case "$OPT" in
            --host) rerun_option_check $# $1; HOST=$2 ; shift 2 ;;
            --interval) rerun_option_check $# $1; INTERVAL=$2 ; shift 2 ;;
            --maxtry) rerun_option_check $# $1; MAXTRY=$2 ; shift 2 ;;
            # help option
            -\?|--help)
                rerun_option_usage
                exit 2
                ;;
            # unrecognized arguments
            *)
              unrecognized_args+=("$OPT")
              shift
              ;;
        esac
    done

    # Set defaultable options.
    [[ -z "$INTERVAL" ]] && INTERVAL="$(rerun_property_get $RERUN_MODULE_DIR/options/interval DEFAULT)"
    # Check required options are set
    [[ -z "$HOST" ]] && { echo >&2 "missing required option: --host" ; return 2 ; }
    [[ -z "$INTERVAL" ]] && { echo >&2 "missing required option: --interval" ; return 2 ; }
    # If option variables are declared exportable, export them.

    # Make unrecognized command line options available in $_CMD_LINE
    if [ ${#unrecognized_args[@]} -gt 0 ]; then
      export _CMD_LINE="${unrecognized_args[@]}"
    fi
    #
    return 0
}


# If not already set, initialize the options variables to null.
: ${HOST:=}
: ${INTERVAL:=}
: ${MAXTRY:=}
# Default command line to null if not set
: ${_CMD_LINE:=}


