#!/usr/bin/env bash

#/ command: waitfor:ping: "wait for ping response from host"
#/ usage: rerun waitfor:ping  --host <""> [ --interval <30>] 
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: HOST INTERVAL

. $RERUN_MODULE_DIR/lib/functions.sh ping || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"


# Command implementation
# ----------------------

until ( ping -c 1 $HOST | grep -q ^64 )
do
   sleep $INTERVAL
   progress_tic .
done

echo "OK: $HOST is pingable."

#
exit $?
