# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Fri Jul 10 18:07:02 PDT 2015
#
#/ usage: waitfor:dir-exists  --interval <30>  --maxtry <10>  --dir <> 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
# 
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {

    while [ "$#" -gt 0 ]; do
        OPT="$1"
        case "$OPT" in
            --interval) rerun_option_check $# $1; INTERVAL=$2 ; shift ;;
            --maxtry) rerun_option_check $# $1; MAXTRY=$2 ; shift ;;
            --dir) rerun_option_check $# $1; DIR=$2 ; shift ;;
            # help option
            -|--*?)
                rerun_option_usage
                exit 2
                ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.
    [ -z "$INTERVAL" ] && INTERVAL="$(rerun_property_get $RERUN_MODULE_DIR/options/interval DEFAULT)"
    [ -z "$MAXTRY" ] && MAXTRY="$(rerun_property_get $RERUN_MODULE_DIR/options/maxtry DEFAULT)"
    # Check required options are set
    [ -z "$INTERVAL" ] && { echo >&2 "missing required option: --interval" ; return 2 ; }
    [ -z "$MAXTRY" ] && { echo >&2 "missing required option: --maxtry" ; return 2 ; }
    [ -z "$DIR" ] && { echo >&2 "missing required option: --dir" ; return 2 ; }
    # If option variables are declared exportable, export them.

    #
    return 0
}


# If not already set, initialize the options variables to null.
: ${INTERVAL:=}
: ${MAXTRY:=}
: ${DIR:=}


