#!/usr/bin/env bash

#/ command: waitfor:dir-exists: "wait for the directory to exist"
#/ usage: rerun waitfor:dir-exists  --interval <30>  --maxtry <10>  --dir <> 
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: INTERVAL MAXTRY DIR

. $RERUN_MODULE_DIR/lib/functions.sh dir-exists || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"


# Command implementation
# ----------------------

declare -i count=0 max=$MAXTRY sleep=$INTERVAL
while (( count <= max ))
do
    if ! test -d "$DIR"
    then  progress_tic "."; # output a progress string.
    else  break; # found successful startup message.
    fi
    (( count += 1 ))  ; # increment attempts counter.    
    (( count == max )) && {
        rerun_log warn "Reached max try directory exists: $DIR. Exiting."
        exit 1
    }
    sleep $sleep; # wait before trying again.
done

echo "OK: $(ls -ld $DIR)"

# Done. Exit with last command exit status.
exit $?

