#!/usr/bin/env bash

#/ command: waitfor:http: "wait for url to become available"
#/ usage: rerun waitfor:http  --url <> 
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: URL

. $RERUN_MODULE_DIR/lib/functions.sh http || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"


# Command implementation
# ----------------------

if ! status_code=$(curl -L -o /dev/null --silent --head --write-out '%{http_code}\n' $URL)
then
	# got an error
	echo "NOT_READY"
	exit 1
fi

case "${status_code}" in
	[2-3]0[0-9])
		echo "OK"
	;;
	40[0-9]) 
		echo "NOT_ALLOWED ($status_code)"
	;;
	5[0-9][0-9]) 	
	echo "NOT_HEALTHY ($status_code)"
	exit 3
esac

# Done. Exit with last command exit status.
exit $?

