# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Fri Jul 10 18:36:22 PDT 2015
#
#/ usage: waitfor:file-contains  --interval <30>  --maxtry <10>  --file <>  --string <> 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
# 
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {

    while [ "$#" -gt 0 ]; do
        OPT="$1"
        case "$OPT" in
            --interval) rerun_option_check $# $1; INTERVAL=$2 ; shift ;;
            --maxtry) rerun_option_check $# $1; MAXTRY=$2 ; shift ;;
            --file) rerun_option_check $# $1; FILE=$2 ; shift ;;
            --string) rerun_option_check $# $1; STRING=$2 ; shift ;;
            # help option
            -|--*?)
                rerun_option_usage
                exit 2
                ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.
    [ -z "$INTERVAL" ] && INTERVAL="$(rerun_property_get $RERUN_MODULE_DIR/options/interval DEFAULT)"
    [ -z "$MAXTRY" ] && MAXTRY="$(rerun_property_get $RERUN_MODULE_DIR/options/maxtry DEFAULT)"
    # Check required options are set
    [ -z "$INTERVAL" ] && { echo >&2 "missing required option: --interval" ; return 2 ; }
    [ -z "$MAXTRY" ] && { echo >&2 "missing required option: --maxtry" ; return 2 ; }
    [ -z "$FILE" ] && { echo >&2 "missing required option: --file" ; return 2 ; }
    [ -z "$STRING" ] && { echo >&2 "missing required option: --string" ; return 2 ; }
    # If option variables are declared exportable, export them.

    #
    return 0
}


# If not already set, initialize the options variables to null.
: ${INTERVAL:=}
: ${MAXTRY:=}
: ${FILE:=}
: ${STRING:=}


