#!/usr/bin/env bash

#/ command: waitfor:file-contains: "wait for the file to contain message"
#/ usage: rerun waitfor:file-contains  --interval <30>  --maxtry <10>  --file <>  --string <> 
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: INTERVAL MAXTRY FILE STRING

. $RERUN_MODULE_DIR/lib/functions.sh file-contains || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}


set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"


# Command implementation
# ----------------------

declare -i count=0 max=$MAXTRY sleep=$INTERVAL

# Keep checking for pattern until we reach max.
while (( count <= max ))
do
    if ! grep "${STRING}" "$FILE"
    then  
        # output a progress string.
        progress_tic "."; 
    else  
        # Success. Found the string in file.
        break; 
    fi
    # increment attempts counter.
    (( count += 1 ))

    # error out if reached max attempts.
    (( count == max )) && {
        rerun_log warn "FAIL: Reached max attempts to find string in $FILE. Exiting."
        exit 1
    }
    # wait interval before trying again.
    sleep "$sleep"
done

# Done. Exit with last command exit status.
exit $?

